# Generated by Django 5.1.3 on 2024-12-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags', null=True),
        ),
    ]
