# Generated by Django 5.1.3 on 2024-11-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_primary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_image',
        ),
    ]
