# Generated by Django 5.1.3 on 2024-11-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(default='**********', max_length=15, null=True),
        ),
    ]
